project_name: jfa-go
release:
    github:
        owner: hrfee
        name: jfa-go
    name_template: "v{{.Version}}"
before:
  hooks:
    - go mod download
    - rm -rf data/web
    - mkdir -p data
    - cp -r static data/web
    - npm install
    - npm install esbuild
    - mkdir -p data/web/css
    - npx esbuild --bundle css/base.css --outfile=./data/web/css/bundle.css --external:remixicon.css --minify
    - cp node_modules/remixicon/fonts/remixicon.css node_modules/remixicon/fonts/remixicon.woff2 data/web/css/
    - cp -r html data/
    - cp -r lang data/
    - python3 scripts/enumerate_config.py -i config/config-base.json -o data/config-base.json
    - python3 scripts/generate_ini.py -i config/config-base.json -o data/config-default.ini
    - python3 scripts/compile_mjml.py -o data/
    - python3 scripts/version.py {{.Version}}
    - npx esbuild --bundle ts/admin.ts --outfile=./data/web/js/admin.js --minify
    - npx esbuild --bundle ts/form.ts --outfile=./data/web/js/form.js --minify
    - npx esbuild --bundle ts/setup.ts --outfile=./data/web/js/setup.js --minify
    - go get -u github.com/swaggo/swag/cmd/swag
    - swag init -g main.go
    - python3 scripts/embed.py internal
builds:
    - dir: ./
      env:
        - CGO_ENABLED=0
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - arm
        - arm64
archives:
  - replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        amd64: x86_64
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "git-{{.ShortCommit}}"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
