# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: jfa-go
release:
    github:
        owner: hrfee
        name: jfa-go
    name_template: "v{{.Version}}"
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    - python3 config/fixconfig.py -i config/config-base.json -o data/config-base.json --version {{.Version}}
    - python3 config/generate_ini.py -i config/config-base.json -o data/config-default.ini
    - python3 -m pip install libsass
    - python3 scss/get_node_deps.py
    - python3 scss/compile.py -y
    - python3 mail/generate.py -y
    - python3 version.py {{.Version}} version.go
builds:
    - dir: ./
      env:
        - CGO_ENABLED=0
      goos:
        - linux
        - windows
        - darwin
      goarch:
        - amd64
        - arm
        - arm64
archives:
  - replacements:
        darwin: Darwin
        linux: Linux
        windows: Windows
        amd64: x86_64
    files:
        - data/*
checksum:
    name_template: 'checksums.txt'
snapshot:
    name_template: "{{ .Tag }}-testing"
changelog:
    sort: asc
    filters:
        exclude:
            - '^docs:'
            - '^test:'
